# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b3c2876480497c548eab0d76635b716e52daad52d1ade702a32af3b038576d50349170d29035e2b7723dbc48e1be719a8e4c0929f50bcf2ee1369c45ce733c

test:
  secret_key_base: eb472ec1485e909c99efd1770a6a1da721ee7621797e17fbd3b860fe3eede8a9adb3af409eeb2122b2316415a8392d3a1bd61c7f5f85a26fb6bcdab3be079aee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
